// =============================================================================
// AUTONOMOUS MELEE COMBAT SYSTEM
// Threat & Aggro System
// =============================================================================
// Soft threat system based on proximity, damage, and behavioral factors.
// NOT MMO hard-taunt. Threat emerges naturally from combat actions.
// =============================================================================

using System.Collections.Generic;
using Combat.Core;
using UnityEngine;

namespace Combat.Threat
{
    /// <summary>
    /// Tracks threat generated by and towards this agent.
    /// Threat influences target selection and defensive priorities.
    /// 
    /// Threat sources (emergent):
    /// - Proximity
    /// - Damage dealt
    /// - Vulnerability (low HP ally nearby)
    /// - Movement blocking
    /// - Protecting allies
    /// - Engagement pressure
    /// </summary>
    [RequireComponent(typeof(CombatAgent))]
    public class ThreatTracker : MonoBehaviour
    {
        [Header("Configuration")]
        [SerializeField] private float _threatDecayRate = 5f;
        [SerializeField] private float _proximityThreatWeight = 1f;
        [SerializeField] private float _damageThreatWeight = 2f;

        private CombatAgent _owner;
        private readonly Dictionary<CombatAgent, float> _threatTable = new Dictionary<CombatAgent, float>();

        public IReadOnlyDictionary<CombatAgent, float> ThreatTable => _threatTable;

        private void Awake()
        {
            _owner = GetComponent<CombatAgent>();
        }

        private void OnEnable()
        {
            CombatEvents.OnDamageDealt += OnDamageDealt;
            CombatEvents.OnEngagementStarted += OnEngagement;
        }

        private void OnDisable()
        {
            CombatEvents.OnDamageDealt -= OnDamageDealt;
            CombatEvents.OnEngagementStarted -= OnEngagement;
        }

        private void Update()
        {
            // Decay threat over time
            var keys = new List<CombatAgent>(_threatTable.Keys);
            foreach (var key in keys)
            {
                if (key == null || !key.IsAlive)
                {
                    _threatTable.Remove(key);
                    continue;
                }
                _threatTable[key] -= _threatDecayRate * Time.deltaTime;
                if (_threatTable[key] <= 0)
                    _threatTable.Remove(key);
            }

            // Proximity threat (passive)
            foreach (var agent in CombatAgentRegistry.AllAgents)
            {
                if (agent == _owner || !agent.IsAlive || !_owner.IsHostileTo(agent)) continue;
                float dist = Vector3.Distance(transform.position, agent.transform.position);
                if (dist < 5f)
                {
                    float proximityThreat = (1f - dist / 5f) * _proximityThreatWeight * Time.deltaTime;
                    AddThreat(agent, proximityThreat);
                }
            }
        }

        /// <summary>Add threat from a source.</summary>
        public void AddThreat(CombatAgent source, float amount)
        {
            if (source == null || source == _owner) return;
            if (!_threatTable.ContainsKey(source))
                _threatTable[source] = 0;
            _threatTable[source] += amount;

            CombatEvents.FireThreatChanged(new ThreatEventArgs
            {
                Source = source,
                Target = _owner,
                ThreatDelta = amount,
                TotalThreat = _threatTable[source]
            });
        }

        /// <summary>Get the highest-threat enemy.</summary>
        public CombatAgent GetHighestThreat()
        {
            CombatAgent highest = null;
            float highestThreat = 0;
            foreach (var kvp in _threatTable)
            {
                if (kvp.Value > highestThreat && kvp.Key != null && kvp.Key.IsAlive)
                {
                    highestThreat = kvp.Value;
                    highest = kvp.Key;
                }
            }
            return highest;
        }

        /// <summary>Get threat level from a specific agent.</summary>
        public float GetThreatFrom(CombatAgent source)
        {
            return _threatTable.TryGetValue(source, out float threat) ? threat : 0f;
        }

        /// <summary>Get total incoming threat.</summary>
        public float GetTotalThreat()
        {
            float total = 0;
            foreach (var kvp in _threatTable)
                total += kvp.Value;
            return total;
        }

        // --- Event Handlers ---

        private void OnDamageDealt(DamageEventArgs args)
        {
            // If we were hit, add threat from attacker
            if (args.Defender == _owner && args.Attacker != null)
            {
                AddThreat(args.Attacker, args.FinalDamage * _damageThreatWeight);
            }
        }

        private void OnEngagement(EngagementEventArgs args)
        {
            // Engagement generates moderate threat
            if (args.Target == _owner)
                AddThreat(args.Initiator, 10f);
        }
    }
}

